#!/bin/bash

function handle {
	#IFS='>>' read -ra event <<< "$1"
	#echo ${event[0]}
	#while IFS=">""," read G1 G2 G3 ; do
		#echo $G1
		#echo $G2
		#echo $G3
	#done < $1
	#case $1 in
		#activewindowv2*) hyprctl dispatch bringactivetotop ;;
		#changefloatingmode*) hyprctl dispatch bringactivetotop ;;
	#esac
	echo $1 | awk -F '>>' '{print $1", "$2", "$3}'
}

socat - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
